[path]
data = "../data/splits/higgs/"
model = "../artifacts/forest/higgs/"
memory_profile = "../results/benchmarks/higgs/memory/"
prediction = "../artifacts/predictions/higgs/"

[name]
profile_label = "HIGGS Training Memory Benchmark"
profile_filename = "higgs_memory_report.txt"

[random_forest]
cc_indices = [] #> `.toml` cannot take `None` as value.
trees_max_depth = 400
bootstrap_balance = "auto"
criterion = "hellinger"
random_state = 42
n_jobs = 8

[iterable_config]
n_trees = [100, 120, 140, 160]
min_leaf_purity = [0.96, 0.97, 0.98, 0.99]
min_samples_split = [10, 15, 20, 25]
min_samples_leaf = [10, 15, 20, 25]